### ISSUE TITLE
Release OTTR 2.0

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#450]
The goal of OTTR 2.0 will be to have something that works really well by the user and is ready to be advertised to the world via manuscript. 

Here's what issues I think need to be addressed for an OTTR 2.0 to go out (This list can be edited depending on what others are thinking): 

- [x]  Customizing OTTRs and their GHA - #436, #445 , #448 and #449 
   - [x]  Add docs about customization set up!
- [x] Rename `ottr` -> `ottr_aide` or something like that - #447 
   - [x]  Update docs and everywhere with update package name
    - [x] Get `ottr_aide` on CRAN? 
- [x] Requests and communication, how should they happen? 
   - [x] Get Google Group fleshed out - #429
   - [x] Make this apparent on the wiki - https://github.com/jhudsl/OTTR_Template/wiki/Getting-Help-(Google-Group)
- [x]  Leanpub docs need to be updated given iframe changes - #381
      - [ ]  This needs to be tested by others who aren't @cansavvy -- like @carriewright11 ?
- [x] Make sure fake Docker fail problem is addressed (I think it should be with #436's resolution) - #430 
- [x] Update course listing - formalize where courses made from OTTR can be listed? Maybe a wiki page for now? #454 
- [x] Add some more quiz checks to ottr https://github.com/jhudsl/ottr/issues/95

- Which OTTR spin offs should be included? There's a basecamp convo about this. 
   - [x] OTTR_Template_Website -> yes?
   - [ ] Templates of Templates? May be nice to have documentation around it but probably should not be advised as a ready to go feature in the manuscript.
 
### Not a requirement, but very nice: 
- [ ] [Intro to OTTR](https://github.com/jhudsl/Intro_to_OTTR) Fleshed out more as its own course and not a direct copy from the wiki like it is now. 
- [ ] Have a tutorial video for setting up the repository -- set up is better with the latest wiki revisions, but the users who I have talked to have expressed that it still is tricky. A quick tutorial video would be good. - #189 

### What I don't think should be a requirement
- mario -- it's going to require a lot of work and its a whole project in itself since we want to separate it from RStudioConnect. So I think its best we drop the mentions of mario from the ottr paper and we consider mario could be its own manuscript at a future date.

**Comment by cansavvy** [comment]
See the list of `before-manuscript` issues [here](https://github.com/jhudsl/OTTR_Template/issues?q=is%3Aopen+is%3Aissue+label%3Abefore-manuscript)
